### ISSUE TITLE
Lots of file（each >1GB) was generated during cp function

### ISSUE THREAD

**Issue by Lee0498** [rikenbit/DelayedTensor#1]
Hi, I am a little confused about the mechanism of out-of-core arithmetic. When I run the function `cp`, thousands of files (each > 1GB) were generated. Is it possible to avoid it?

**Comment by kokitsuyuzaki** [comment]
Hello, @Lee0498 
Out-of-core is a technique in which, when data is too large to be loaded in memory, only small block tensors are loaded on memory, and the results of intermediate calculations are temporarily stored in HDD.
DelayedTensor is a framework that allows users to perform out-of-core tensor computation and decomposition without being aware of it.
Due to the nature of these calculations, the temporal files in the middle of the calculation must be saved on the HDD.

**Comment by Lee0498** [comment]
Thanks! I can figure out why there are lots of temporary files. I still have a question about `cp` function with `DelayedTensor`. The while loop is used to iteratively decomposition the tensor until convergence.

**Comment by Lee0498** [comment]
Thanks! I have figured out why there are lots of temporary files. 
I still have a question about `cp` function with DelayedTensor. The while loop is used to iteratively decompose the tensor until convergence. Each loop will generate a series of temporary files. However, not every temporary file is used in the next loop. Is it possible to timely delete those unused files for saving HDD storage?

**Comment by kokitsuyuzaki** [comment]
Ok, I'll check whether it is possible.

**Comment by kokitsuyuzaki** [comment]
The implementation you suggested is possible, but it would be a loss of computation time to include a process to delete the file in every loop.

The current implementation deletes all temporary data when all calculations are done, and I feel that is sufficient.

The concept of DelayedTensor is to process large tensor data that cannot be stored in memory in an out-of-core manner while keeping the data on the hard disk, so it is not assumed that the hard disk does not have sufficient capacity.

Therefore, I will leave the implementation as it is.
